# coding: utf-8

"""
    DBIT API

    DBIT API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from gen.src.openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="DBIT API",
    description="DBIT API",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)
